### ISSUE TITLE
Unable to satisfy fvcore>=0.1.1 during installation

### ISSUE THREAD

**Issue by CedricPicron** [facebookresearch/detectron2#1418]
## Instructions To Reproduce the 🐛 Bug:

1. what changes you made (`git diff`) or what code you wrote
```
No change.
```
2. what exact command you run: python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
3. what you observed (including __full logs__):
```
ERROR: Could not find a version that satisfies the requirement fvcore>=0.1.1 (from detectron2==0.1.2) (from versions: 0.1.dev191230, 0.1.dev191231, 0.1.dev200101, 0.1.dev200102, 0.1.dev200103, 0.1.dev200104, 0.1.dev200106, 0.1.dev200107, 0.1.dev200108, 0.1.dev200109, 0.1.dev200110, 0.1.dev200111, 0.1.dev200112, 0.1.dev200113, 0.1.dev200114, 0.1.dev200201, 0.1.dev200202, 0.1.dev200203, 0.1.dev200204, 0.1.dev200205, 0.1.dev200206, 0.1.dev200207, 0.1.dev200208, 0.1.dev200209, 0.1.dev200210, 0.1.dev200211, 0.1.dev200212, 0.1.dev200213, 0.1.dev200214, 0.1.dev200215, 0.1.dev200216, 0.1.dev200217, 0.1.dev200218, 0.1.dev200224, 0.1.dev200226, 0.1.dev200227, 0.1.dev200228, 0.1.dev200229, 0.1.dev200301, 0.1.dev200302, 0.1.dev200303, 0.1.dev200304, 0.1.dev200305, 0.1.dev200306, 0.1.dev200307, 0.1.dev200308, 0.1.dev200316, 0.1.dev200319, 0.1.dev200322, 0.1.dev200323, 0.1.dev200324, 0.1.dev200325, 0.1.dev200407, 0.1.dev200408, 0.1.dev200409, 0.1.dev200410, 0.1.dev200413, 0.1.dev200414, 0.1.dev200415, 0.1.dev200416, 0.1.dev200417, 0.1.dev200418, 0.1.dev200420, 0.1.dev200424, 0.1.dev200502, 0.1.dev200504, 0.1.dev200505, 0.1.dev200506, 0.1.1.dev200512)
ERROR: No matching distribution found for fvcore>=0.1.1 (from detectron2==0.1.2)
```

Note that it finds fvcore==0.1.1.dev200512, but this apparently does not satisfy fvcore>=0.1.1.

**Comment by minan19605** [comment]
I have same issue today. 
1. I use the below steps to install fvcore:
git clone https://github.com/facebookresearch/fvcore
cd fvcore &&  python setup.py install. 

2. then I try to install detectron2. I have same issue.

3. I run pip uninstall fvcore and try the: pip install fvcore.
4. Then I can install detections successfully.

**Comment by gosiqueira** [comment]
A few weeks ago I used detectron2 install to run VideoPose3D and it worked perfectly.
Today, I'm setting up a new project and I'm also having this issue with fvcore.

**Comment by 6etacat** [comment]
I am also encountering the same issue.

**Comment by minan19605** [comment]
Try below method:
1. pip uninstall fvcore;
2. pip install fvcore;

**Comment by ppwwyyxx** [comment]
We'll fix the dependencies. But just `pip install -U fvcore` would work.

**Comment by LenHu0725** [comment]
Same issue
After run `pip install -U fvcore` successfully, there is still a problem.

```
ERROR: Could not find a version that satisfies the requirement fvcore>=0.1.1 (from detectron2==0.1.2) (from versions: 0.1.dev191230, 0.1.dev191231, 0.1.dev200101, 0.1.dev200102, 0.1.dev200103, 0.1.dev200104, 0.1.dev200106, 0.1.dev200107, 0.1.dev200108, 0.1.dev200109, 0.1.dev200110, 0.1.dev200111, 0.1.dev200112, 0.1.dev200113, 0.1.dev200114, 0.1.dev200201, 0.1.dev200202, 0.1.dev200203, 0.1.dev200204, 0.1.dev200205, 0.1.dev200206, 0.1.dev200207, 0.1.dev200208, 0.1.dev200209, 0.1.dev200210, 0.1.dev200211, 0.1.dev200212, 0.1.dev200213, 0.1.dev200214, 0.1.dev200215, 0.1.dev200216, 0.1.dev200217, 0.1.dev200218, 0.1.dev200224, 0.1.dev200226, 0.1.dev200227, 0.1.dev200228, 0.1.dev200229, 0.1.dev200301, 0.1.dev200302, 0.1.dev200303, 0.1.dev200304, 0.1.dev200305, 0.1.dev200306, 0.1.dev200307, 0.1.dev200308, 0.1.dev200316, 0.1.dev200319, 0.1.dev200322, 0.1.dev200323, 0.1.dev200324, 0.1.dev200325, 0.1.dev200407, 0.1.dev200408, 0.1.dev200409, 0.1.dev200410, 0.1.dev200413, 0.1.dev200414, 0.1.dev200415, 0.1.dev200416, 0.1.dev200417, 0.1.dev200418, 0.1.dev200420, 0.1.dev200424, 0.1.dev200502, 0.1.dev200504, 0.1.dev200505, 0.1.dev200506, 0.1.1.dev200512)
ERROR: No matching distribution found for fvcore>=0.1.1 (from detectron2==0.1.2)
```

**Comment by ppwwyyxx** [comment]
Please ignore that for now and use `pip install --no-deps  ...` for detectron2.

**Comment by ppwwyyxx** [comment]
should work now:
```
$pip install 'fvcore>=0.1.1'
Installing collected packages: fvcore
Successfully installed fvcore-0.1.1.post200513
```

**Comment by LenHu0725** [comment]
> Please ignore that for now and use `pip install --no-deps ...` for detectron2.

I solved this problem after check CUDA environment in `~ / .bashrc`.

**Comment by 17sarf** [comment]
I am trying to install this on a Windows 10 machine and I have tried the methods above to fix the issue but i still get the same error:

`ERROR: Could not find a version that satisfies the requirement detectron2==0.1.3 (from versions: none)
ERROR: No matching distribution found for detectron2==0.1.3`

**Comment by Shubhendu-Jena** [comment]
Still facing the same issue : 
ERROR: Could not find a version that satisfies the requirement fvcore==0.1.2 (from detectron2==0.3)
ERROR: No matching distribution found for fvcore==0.1.2 (from detectron2==0.3)
Did anyone manage to figure out how to resolve this?

**Comment by Haow235** [comment]
Same issue from yesterday, "pip install --no-deps ..." doesn't work.

> Still facing a similar same issue, even though I have installed fvcore successfully :
> 
> ERROR: Could not find a version that satisfies the requirement fvcore==0.1.2 (from detectron2==0.3)
> ERROR: No matching distribution found for fvcore==0.1.2 (from detectron2==0.3)
> 
> Did anyone manage to figure out how to resolve this?

**Comment by mahmoudhanoraa** [comment]
uninstall fvcore, then pip install --no-deps worked for me, then I installed the missed dependancies myself with pip install

**Comment by zptang1210** [comment]
> uninstall fvcore, then pip install --no-deps worked for me, then I installed the missed dependancies myself with pip install

This still doesn't work for me.
But I tried to use the command from the fvcore repo directly to install this package, and then it works.
pip install -U 'git+https://github.com/facebookresearch/fvcore'
