### ISSUE TITLE
Error when resume from .pth: BlockingIOError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by Mactarvish** [facebookresearch/detectron2#3900]
I'm trying to resume my training from an just saved .pth, and detectron 2 reported such error: 

2. What exact command you run:
``` python train_net.py --resume ```
3. __Full logs__ or other relevant observations:
```
[01/19 00:36:37 d2.data.build]: Removed 3 images with no usable annotations. 40716 images left.
[01/19 00:36:39 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice')]
[01/19 00:36:39 d2.data.build]: Using training sampler TrainingSampler
[01/19 00:36:41 d2.data.common]: Serializing 40716 elements to byte tensors and concatenating them all ...
[01/19 00:36:42 d2.data.common]: Serialized dataset takes 52.53 MiB
[01/19 00:36:42 fvcore.common.checkpoint]: [Checkpointer] Loading from /data1/jim/detectron2/projects/common_det/ai_mark/model_0009999.pth ...
[01/19 00:36:42 d2.engine.train_loop]: Starting training from iteration 10000
OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data1/jim/detectron2/projects/common_det/train_net.py", line 22, in <module>
    import torch
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/site-packages/torch/__init__.py", line 196, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import
OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 6 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 8 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 9 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 10 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 11 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 12 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 13 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 14 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 15 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 16 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 17 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 18 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 19 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 20 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 21 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 22 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 23 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 24 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 25 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 26 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 27 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 28 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 29 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 30 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 31 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 32 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 33 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 34 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 35 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 36 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 37 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 38 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 39 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 40 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 41 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 42 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 43 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 44 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 45 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 46 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 47 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 48 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 49 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 50 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 51 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 52 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 53 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 54 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 55 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 56 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 57 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 58 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 59 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 60 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 61 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 62 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data1/jim/detectron2/projects/common_det/train_net.py", line 22, in <module>
    import torch
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/site-packages/torch/__init__.py", line 196, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import
OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1287654 current, 1287654 max
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data1/jim/detectron2/projects/common_det/train_net.py", line 22, in <module>
    import torch
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/site-packages/torch/__init__.py", line 196, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f80ee456320>
Traceback (most recent call last):
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1291, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "train_net.py", line 258, in <module>
    args=(args,),
  File "/data1/jim/detectron2/detectron2/engine/launch.py", line 79, in launch
    daemon=False,
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/data1/jim/detectron2/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/data1/jim/detectron2/projects/common_det/train_net.py", line 247, in main
    return trainer.train()
  File "/data1/jim/detectron2/detectron2/engine/defaults.py", line 509, in train
    super().train(self.start_iter, self.max_iter)
  File "/data1/jim/detectron2/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/data1/jim/detectron2/detectron2/engine/defaults.py", line 519, in run_step
    self._trainer.run_step()
  File "/data1/jim/detectron2/detectron2/engine/train_loop.py", line 267, in run_step
    data = next(self._data_loader_iter)
  File "/data1/jim/detectron2/detectron2/data/common.py", line 234, in __iter__
    for d in self.dataset:
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 914, in __init__
    w.start()
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 59, in _launch
    cmd, self._fds)
  File "/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/util.py", line 455, in spawnv_passfds
    False, False, None)
BlockingIOError: [Errno 11] Resource temporarily unavailable

(detectron2) jim@VM-16-9-ubuntu:/data1/jim/detectron2/projects/common_det$ /data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 53 leaked semaphores to clean up at shutdown
  len(cache))
/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 53 leaked semaphores to clean up at shutdown
  len(cache))
/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 53 leaked semaphores to clean up at shutdown
  len(cache))
/data1/jim/miniconda3/envs/detectron2/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 62 leaked semaphores to clean up at shutdown
  len(cache))
```

## Environment:
cuda 10.1
torch                   1.8.0+cu101
torchvision             0.9.0+cu101
detectron2              0.6
numpy                   1.21.5
Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/main/detectron2/utils/collect_env.py && python collect_env.py
```

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues

**Comment by Mactarvish** [comment]
Solved by ```ps aux | grep 'import spawn_main;' | grep -v grep | cut -c 9-15 | xargs kill -9```

**Comment by fingertap** [comment]
So this is caused by the uncleaned jobs? I have a newly created k8s pod, and I encountered this error after training for several epochs.

**Comment by Johnqczhang** [comment]
> Solved by `ps aux | grep 'import spawn_main;' | grep -v grep | cut -c 9-15 | xargs kill -9`

I met the same issue when starting the evaluation after 5000 iterations during training. I tried the solution above before the training but the issue still occurs.

1. Full runnable code or full changes you made:
``` yaml
DATALOADER.NUM_WORKERS: 8
TEST.EVAL_PERIOD: 5000
```

2. What exact command you run:
`python tools/train_net.py --num-gpus 2 --config-file configs/model_R50.yaml`

3. Full logs or other relevant observations:
``` shell
[05/08 04:58:14 d2.data.common]: Serializing 5000 elements to byte tensors and concatenating them all ...                                                                [41/1785]
[05/08 04:58:14 d2.data.common]: Serialized dataset takes 19.10 MiB
WARNING [05/08 04:58:14 d2.evaluation.coco_evaluation]: COCO Evaluator instantiated using config, this is deprecated behavior. Please pass in explicit arguments instead.
[05/08 04:58:15 d2.evaluation.evaluator]: Start inference on 2500 batches
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb3d26e0280>
Traceback (most recent call last):
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1295, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "tools/train_net.py", line 262, in <module>
    launch(
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/disk1/johnqczhang/exp/adet/tools/train_net.py", line 256, in main
    return trainer.train()
  File "/disk1/johnqczhang/exp/adet/tools/train_net.py", line 103, in train
    self.train_loop(self.start_iter, self.max_iter)
  File "/disk1/johnqczhang/exp/adet/tools/train_net.py", line 93, in train_loop
    self.after_step()
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/detectron2/engine/train_loop.py", line 180, in after_step
    h.after_step()
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/detectron2/engine/hooks.py", line 552, in after_step
    self._do_eval()
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/detectron2/engine/hooks.py", line 525, in _do_eval
    results = self._func()
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 453, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 608, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/detectron2/evaluation/evaluator.py", line 149, in inference_on_dataset
    for idx, inputs in enumerate(data_loader):
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 918, in __init__
    w.start()
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 58, in _launch
    self.pid = util.spawnv_passfds(spawn.get_executable(),
  File "/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/multiprocessing/util.py", line 452, in spawnv_passfds
    return _posixsubprocess.fork_exec(
BlockingIOError: [Errno 11] Resource temporarily unavailable
```

## Environment:
``` shell
[05/08 01:44:01 detectron2]: Environment info:
----------------------  ------------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0]
numpy                   1.21.4
detectron2              0.6 @/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 10.2
detectron2 arch flags   3.7, 5.0, 5.2, 6.0, 6.1, 7.0, 7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.10.0+cu102 @/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0,1                 Tesla V100-PCIE-32GB (arch=7.0)
Driver version          440.64.00
CUDA_HOME               /usr/local/cuda-10.2
Pillow                  8.4.0
torchvision             0.11.0+cu102 @/home/johnqczhang/opt/anaconda3/envs/adet/lib/python3.8/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.5.post20211023
iopath                  0.1.9
cv2                     4.5.4
----------------------  ------------------------------------------------------------------------------------------------

**Comment by ppwwyyxx** [comment]
`[BlockingIOError: [Errno 11] Resource temporarily unavailable]` during fork is a system limitation. See https://access.redhat.com/solutions/22105 for some common cause and solutions..

**Comment by Johnqczhang** [comment]
> `[BlockingIOError: [Errno 11] Resource temporarily unavailable]` during fork is a system limitation. See https://access.redhat.com/solutions/22105 for some common cause and solutions..

Thanks for your hint! The newly error log shown below provides useful info. The issue has been solved by adding `OMP_NUM_THREADS=2` before the running command. Thanks again!
``` bash
OpenBLAS blas_thread_init: pthread_create failed for thread 55 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1544645 max
OpenBLAS blas_thread_init: pthread_create failed for thread 56 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1544645 max
OpenBLAS blas_thread_init: pthread_create failed for thread 57 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1544645 max
OpenBLAS blas_thread_init: pthread_create failed for thread 58 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1544645 max
```

**Comment by jinx2018** [comment]
```python
import shutil
shutil._USE_CP_SENDFILE = False
```
